<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hanne Oberman (original by Gerko Vink and Stef van Buuren )">

<title>A one-day crash course in mice</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#multiple-imputation-with-mice" id="toc-multiple-imputation-with-mice" class="nav-link active" data-scroll-target="#multiple-imputation-with-mice">Multiple imputation with <code>mice</code></a></li>
  <li><a href="#repeated-analysis-in-mice-1" id="toc-repeated-analysis-in-mice-1" class="nav-link" data-scroll-target="#repeated-analysis-in-mice-1">Repeated analysis in <code>mice</code> #1</a></li>
  <li><a href="#the-boys-data-set" id="toc-the-boys-data-set" class="nav-link" data-scroll-target="#the-boys-data-set">The <code>boys</code> data set</a></li>
  <li><a href="#repeated-analysis-in-mice-2" id="toc-repeated-analysis-in-mice-2" class="nav-link" data-scroll-target="#repeated-analysis-in-mice-2">Repeated analysis in <code>mice</code> #2</a></li>
  <li><a href="#the-importance-of-the-imputation-model" id="toc-the-importance-of-the-imputation-model" class="nav-link" data-scroll-target="#the-importance-of-the-imputation-model">The importance of the imputation model</a></li>
  <li><a href="#passive-imputation" id="toc-passive-imputation" class="nav-link" data-scroll-target="#passive-imputation">Passive Imputation</a>
  <ul class="collapse">
  <li><a href="#for-fun" id="toc-for-fun" class="nav-link" data-scroll-target="#for-fun">For fun</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#additional-materials" id="toc-additional-materials" class="nav-link" data-scroll-target="#additional-materials">Additional materials</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A one-day crash course in <code>mice</code></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hanne Oberman (original by Gerko Vink and Stef van Buuren <a href="https://zenodo.org/badge/latestdoi/271731959"><img src="https://zenodo.org/badge/271731959.svg" class="img-fluid"></a>) </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<hr>
<p>The aim of this guide is to make you familiar with <a href="https://github.com/amices/mice">mice</a> in <code>R</code> and to enhance your understanding of multiple imputation, in general. You will learn how to perform and inspect multiple imputations and how to pool the results of analyses performed on multiply-imputed data, how to approach different types of data and how to avoid some of the pitfalls many data scientists may fall into. The main objective is to increase your knowledge and understanding on applications of multiple imputation.</p>
<p>We start by loading (with <code>library()</code>) the necessary packages and fixing the random seed to allow for our outcomes to be replicable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)    <span class="co"># data imputation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmice)  <span class="co"># plotting </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># plotting </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)   <span class="co"># data manipulation</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)   <span class="co"># functional programming</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<section id="multiple-imputation-with-mice" class="level1">
<h1>Multiple imputation with <code>mice</code></h1>
<hr>
<p>We fix the RNG seed to allow for replication of the below results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>mice</code> package contains several datasets. Once the package is loaded, these datasets can be used. Have a look at the <code>nhanes</code> dataset (Schafer, 1997, Table 6.14) by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nhanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age  bmi hyp chl
1    1   NA  NA  NA
2    2 22.7   1 187
3    1   NA   1 187
4    3   NA  NA  NA
5    1 20.4   1 113
6    3   NA  NA 184
7    1 22.5   1 118
8    1 30.1   1 187
9    2 22.0   1 238
10   2   NA  NA  NA
11   1   NA  NA  NA
12   2   NA  NA  NA
13   3 21.7   1 206
14   2 28.7   2 204
15   1 29.6   1  NA
16   1   NA  NA  NA
17   3 27.2   2 284
18   2 26.3   2 199
19   1 35.3   1 218
20   3 25.5   2  NA
21   1   NA  NA  NA
22   1 33.2   1 229
23   1 27.5   1 131
24   3 24.9   1  NA
25   2 27.4   1 186</code></pre>
</div>
</div>
<p>The <code>nhanes</code> dataset is a small data set with non-monotone missing values. It contains 25 observations on four variables: <em>age group</em>, <em>body mass index</em>, <em>hypertension</em> and <em>cholesterol (mg/dL)</em>.</p>
<p>To learn more about the data, use one of the two following help commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(nhanes)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>?nhanes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>nhanes</code> dataset is incomplete. We can visualize the missing data patterns by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">md.pattern</span>(nhanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   age hyp bmi chl   
13   1   1   1   1  0
3    1   1   1   0  1
1    1   1   0   1  1
1    1   0   0   1  2
7    1   0   0   0  3
     0   8   9  10 27</code></pre>
</div>
</div>
<p>For more informative axis labels, we can use the equivalent <code>ggmice</code> function <code>plot_pattern()</code> as follows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_pattern</span>(nhanes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Although the most common pattern is the one where all variables are observed, the majority of cases have at least one missing value.</p>
<hr>
<p><strong>1. Vary the number of imputations, such that the <code>nhanes</code> set is imputed <span class="math inline">\(m=3\)</span> times. </strong></p>
<p>The number of imputed data sets can be specified by the <code>m = ...</code> argument. For example, to create just three imputed data sets, specify</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">m =</span> <span class="dv">3</span>, <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>print = FALSE</code> argument omits printing of the iteration history from the output. The main reason to omit printing here is to save space in the document.</p>
<hr>
<p><strong>2. Change the predictor matrix</strong></p>
<p>The predictor matrix is a square matrix that specifies the variables that can be used to impute each incomplete variable. Let us have a look at the predictor matrix that was used</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>imp<span class="sc">$</span>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age bmi hyp chl
age   0   1   1   1
bmi   1   0   1   1
hyp   1   1   0   1
chl   1   1   1   0</code></pre>
</div>
</div>
<p>Each variable in the data has a row and a column in the predictor matrix. A value <code>1</code> indicates that the column variable was used to impute the row variable. For example, the <code>1</code> at entry <code>[bmi, age]</code> indicates that variable <code>age</code> was used to impute the incomplete variable <code>bmi</code>. Note that the diagonal is zero because a variable is not allowed to impute itself. The row of <code>age</code> is redundant, because there were no missing values in <code>age</code>. Even though predictor relations are specified for <code>age</code>, <code>mice</code> will not use these relations because it will never overwrite the observed values with imputations. <code>mice</code> gives you complete control over the predictor matrix, enabling you to choose your own predictor relations. This can be very useful, for example, when you have many variables or when you have clear ideas or prior knowledge about relations in the data at hand.</p>
<p>There are two ways in which you can create a predictor matrix in <code>mice</code>:</p>
<ul>
<li>A. You can grab the <code>predictorMatrix</code> from every object returned by <code>mice()</code>:</li>
</ul>
<p>For example, we can use any <code>mice()</code> object fitted to the data to grab the <code>predictorMatrix</code> or we can use mice to quickly initialize a predictor matrix, and change it afterwards, without running the algorithm. This latter approach can be done by setting the maximum number of iterations to <code>maxit=0</code>. This leaves the algorithm at initialization, but generates the necessary inner objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ini <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">maxit =</span> <span class="dv">0</span>, <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> ini<span class="sc">$</span>pred</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age bmi hyp chl
age   0   1   1   1
bmi   1   0   1   1
hyp   1   1   0   1
chl   1   1   1   0</code></pre>
</div>
</div>
<p>The object <code>pred</code> contains the predictor matrix from an initial run of <code>mice</code> with zero iterations. It is a square matrix that captures the information about which variables (in the rows) are imputed based on which predictors (in the columns).</p>
<ul>
<li>B. We can use <code>make.predictorMatrix()</code> to generate a predictor matrix from any incomplete data set.</li>
</ul>
<p>For example,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">make.predictorMatrix</span>(nhanes)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age bmi hyp chl
age   0   1   1   1
bmi   1   0   1   1
hyp   1   1   0   1
chl   1   1   1   0</code></pre>
</div>
</div>
<p>Altering the predictor matrix and returning it to the mice algorithm is very simple. For example, the following code removes the variable <code>hyp</code> from the set of predictors, but still leaves it to be predicted by the other variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pred[, <span class="st">"hyp"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age bmi hyp chl
age   0   1   0   1
bmi   1   0   0   1
hyp   1   1   0   1
chl   1   1   0   0</code></pre>
</div>
</div>
<p>Use your new predictor matrix in <code>mice()</code> as follows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">predictorMatrix =</span>  pred, <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, we can easily feed the new matrix <code>pred</code> to <code>mice</code>. We can also abbreviate the logical operator in the argument <code>print = FALSEALSE</code>.</p>
<p>There is a <code>quickpred()</code> function that applies a quick selection procedure of predictors, which can be handy for datasets containing many variables. See <code>?quickpred</code> for more info. Selecting predictors according to data relations with a minimum correlation of <span class="math inline">\(\rho=.30\)</span> can be done by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ini <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">pred =</span> <span class="fu">quickpred</span>(nhanes, <span class="at">mincor =</span> .<span class="dv">3</span>), <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ini<span class="sc">$</span>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age bmi hyp chl
age   0   0   0   0
bmi   1   0   0   1
hyp   1   0   0   1
chl   1   1   1   0</code></pre>
</div>
</div>
<p>For large predictor matrices, it can be useful to export them to dedicated spreadsheet software like e.g.&nbsp;Microsoft Excel for easier configuration (e.g.&nbsp;see the <a href="https://cran.r-project.org/web/packages/xlsx/index.html"><code>xlsx</code> package</a> for easy exporting and importing of Excel files). Importing data is straightforward in <code>RStudio</code> through <code>File</code> &gt; <code>Import Dataset</code>.</p>
<p>You can visualize the predictor matrix with the <code>ggmice</code> function <code>plot_pred()</code> as follows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_pred</span>(pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>3. Inspect the convergence of the algorithm</strong></p>
<p>The <code>mice()</code> function implements an iterative Markov Chain Monte Carlo type of algorithm. Let us have a look at the trace lines generated by the algorithm to study convergence:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The plot shows the mean (left) and standard deviation (right) of the imputed values only. In general, we would like the streams to intermingle (mixing) and be free of any trends at the later iterations (non-stationary). We inspect trends for the imputed values alone, because the observed data does not change. In our case we cannot speak of convergence, especially not for <code>bmi</code>. More iterations or a different model are needed.</p>
<p>The <code>mice</code> algorithm uses random sampling, and therefore, the results will be (perhaps slightly) different if we repeat the imputations with different seeds. In order to get identical <code>mice</code> objects between calls, we can fix the use the <code>seed</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes, <span class="at">seed =</span> <span class="dv">123</span>, <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>where <code>123</code> is some arbitrary number that you can choose yourself. Rerunning this command will always yields the same imputed values.</p>
<hr>
<p><strong>4. Change the imputation method</strong></p>
<p>For each column, the algorithm requires a specification of the imputation method. To see which method was used by default:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>imp<span class="sc">$</span>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age   bmi   hyp   chl 
   "" "pmm" "pmm" "pmm" </code></pre>
</div>
</div>
<p>The variable <code>age</code> is complete and therefore not imputed, denoted by the <code>""</code> empty string. The other variables have method <code>pmm</code>, which stands for <em>predictive mean matching</em>, the default in <code>mice</code> for numerical and integer data.</p>
<p>In reality, the <code>nhanes</code> data are better described a as mix of numerical and categorical data. Let us take a look at the <code>nhanes2</code> data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nhanes2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    age          bmi          hyp          chl       
 20-39:12   Min.   :20.40   no  :13   Min.   :113.0  
 40-59: 7   1st Qu.:22.65   yes : 4   1st Qu.:185.0  
 60-99: 6   Median :26.75   NA's: 8   Median :187.0  
            Mean   :26.56             Mean   :191.4  
            3rd Qu.:28.93             3rd Qu.:212.0  
            Max.   :35.30             Max.   :284.0  
            NA's   :9                 NA's   :10     </code></pre>
</div>
</div>
<p>and the structure of the data frame</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(nhanes2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   25 obs. of  4 variables:
 $ age: Factor w/ 3 levels "20-39","40-59",..: 1 2 1 3 1 3 1 1 2 2 ...
 $ bmi: num  NA 22.7 NA NA 20.4 NA 22.5 30.1 22 NA ...
 $ hyp: Factor w/ 2 levels "no","yes": NA 1 1 NA 1 NA 1 1 1 NA ...
 $ chl: num  NA 187 187 NA 113 184 118 187 238 NA ...</code></pre>
</div>
</div>
<p>Variable <code>age</code> consists of 3 age categories, while variable <code>hyp</code> is binary. The <code>mice()</code> function takes these properties automatically into account. Impute the <code>nhanes2</code> dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes2, <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>imp<span class="sc">$</span>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      bmi      hyp      chl 
      ""    "pmm" "logreg"    "pmm" </code></pre>
</div>
</div>
<p>Notice that <code>mice</code> has set the imputation method for variable <code>hyp</code> to <code>logreg</code>, which implements multiple imputation by <em>logistic regression</em>.</p>
<p>An up-to-date overview of the methods in mice can be found by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">methods</span>(mice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>no methods found</code></pre>
</div>
</div>
<p>Let us change the imputation method for <code>bmi</code> to Bayesian normal linear regression imputation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>meth <span class="ot">&lt;-</span> <span class="fu">make.method</span>(nhanes2)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      bmi      hyp      chl 
      ""    "pmm" "logreg"    "pmm" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"bmi"</span>] <span class="ot">&lt;-</span> <span class="st">"norm"</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      bmi      hyp      chl 
      ""   "norm" "logreg"    "pmm" </code></pre>
</div>
</div>
<p>The new methods vector can be visualized with the predictor matrix by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_pred</span>(pred, <span class="at">method =</span> meth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, we can run the imputations again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(nhanes2, <span class="at">meth =</span> meth, <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and we may again plot trace lines to study convergence</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>5. Extend the number of iterations</strong></p>
<p>Though using just five iterations (the default) often works well in practice, we need to extend the number of iterations of the <code>mice</code> algorithm to confirm that there is no trend and that the trace lines intermingle well. We can increase the number of iterations to 40 by running 35 additional iterations using the <code>mice.mids()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>imp40 <span class="ot">&lt;-</span> <span class="fu">mice.mids</span>(imp, <span class="at">maxit =</span> <span class="dv">35</span>, <span class="at">print =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp40)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>6. Further diagnostic checking.</strong></p>
<p>Generally, one would prefer for the imputed data to be plausible values, i.e.&nbsp;values that could have been observed if they had not been missing. In order to form an idea about plausibility, one may check the imputations and compare them against the observed values. If we are willing to assume that the data are missing completely at random (MCAR), then the imputations should have the same distribution as the observed data. In general, distributions may be different because the missing data are MAR (or even MNAR). However, very large discrepancies need to be screened. Let us plot the observed and imputed data of <code>chl</code> by</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggmice</span>(imp, <span class="fu">aes</span>(<span class="at">x =</span> .imp, <span class="at">y =</span> chl)) <span class="sc">+</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> .<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The convention is to plot observed data in blue and the imputed data in red. The figure graphs the data values of <code>chl</code> before and after imputation. Since the PMM method draws imputations from the observed data, imputed values have the same gaps as in the observed data, and are always within the range of the observed data. The figure indicates that the distributions of the imputed and the observed values are similar. The observed data have a particular feature that, for some reason, the data cluster around the value of 187. The imputations reflect this feature, and are close to the data. Under MCAR, univariate distributions of the observed and imputed data are expected to be identical. Under MAR, they can be different, both in location and spread, but their multivariate distribution is assumed to be identical. There are many other ways to look at the imputed data.</p>
<p>The following commands create a the graph from the previous step for <code>bmi</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>purrr<span class="sc">::</span><span class="fu">map</span>(<span class="fu">names</span>(imp<span class="sc">$</span>data), <span class="sc">~</span>{</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggmice</span>(imp, <span class="fu">aes</span>(<span class="at">x =</span> .imp, <span class="at">y =</span> .data[[.x]])) <span class="sc">+</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>(<span class="at">width =</span> .<span class="dv">1</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[2]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[3]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
[[4]]</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-28-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Remember that <code>bmi</code> was imputed by Bayesian linear regression and (the range of) imputed values may therefore be different than observed values.</p>
<hr>
</section>
<section id="repeated-analysis-in-mice-1" class="level1">
<h1>Repeated analysis in <code>mice</code> #1</h1>
<hr>
<p><strong>7. Perform the following regression analysis on the multiply imputed data and assign the result to object <code>fit</code>. </strong></p>
<p><span class="math display">\[\text{bmi} = \beta_0 + \beta_1 \text{chl} + \epsilon\]</span></p>
<p>Let’s run the above model on the imputed data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">with</span>(imp, <span class="fu">lm</span>(bmi <span class="sc">~</span> chl))</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>call :
with.mids(data = imp, expr = lm(bmi ~ chl))

call1 :
mice(data = nhanes2, method = meth, printFlag = FALSE)

nmis :
age bmi hyp chl 
  0   9   8  10 

analyses :
[[1]]

Call:
lm(formula = bmi ~ chl)

Coefficients:
(Intercept)          chl  
   18.67386      0.04157  


[[2]]

Call:
lm(formula = bmi ~ chl)

Coefficients:
(Intercept)          chl  
   23.24993      0.01357  


[[3]]

Call:
lm(formula = bmi ~ chl)

Coefficients:
(Intercept)          chl  
   20.44776      0.02952  


[[4]]

Call:
lm(formula = bmi ~ chl)

Coefficients:
(Intercept)          chl  
   19.98444      0.03425  


[[5]]

Call:
lm(formula = bmi ~ chl)

Coefficients:
(Intercept)          chl  
   22.70463      0.02237  </code></pre>
</div>
</div>
<p>The <code>fit</code> object contains the regression summaries for each data set. The new object <code>fit</code> is actually of class <code>mira</code> (<em>multiply imputed repeated analyses</em>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mira"   "matrix"</code></pre>
</div>
</div>
<p>Use the <code>ls()</code> function to what out what is in the object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "analyses" "call"     "call1"    "nmis"    </code></pre>
</div>
</div>
<p>Suppose we want to find the regression model fitted to the second imputed data set. It can be found as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit<span class="sc">$</span>analyses[[<span class="dv">2</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bmi ~ chl)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.2983  -3.5392   0.0969   2.6823   9.0924 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 23.24993    4.70339   4.943 5.37e-05 ***
chl          0.01357    0.02332   0.582    0.566    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.965 on 23 degrees of freedom
Multiple R-squared:  0.01451,   Adjusted R-squared:  -0.02834 
F-statistic: 0.3385 on 1 and 23 DF,  p-value: 0.5663</code></pre>
</div>
</div>
<hr>
<p><strong>8. Pool the analyses from object <code>fit</code>. </strong></p>
<p>Pooling the repeated regression analyses can be done simply by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pool.fit <span class="ot">&lt;-</span> <span class="fu">pool</span>(fit)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pool.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         term    estimate  std.error statistic       df      p.value
1 (Intercept) 21.01212500 4.92594605  4.265602 15.18609 0.0006597528
2         chl  0.02825496 0.02535686  1.114292 13.89920 0.2840518295</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>pool.fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mipo    m = 5 
         term m    estimate         ubar            b            t dfcom
1 (Intercept) 5 21.01212500 1.985061e+01 3.6786158400 2.426494e+01    23
2         chl 5  0.02825496 5.033792e-04 0.0001163261 6.429706e-04    23
        df       riv    lambda       fmi
1 15.18609 0.2223781 0.1819225 0.2718899
2 13.89920 0.2773085 0.2171038 0.3097586</code></pre>
</div>
</div>
<p>which gives the relevant pooled regression coefficients and parameters, as well as the fraction of information about the coefficients missing due to non-response (<code>fmi</code>) and the proportion of the variation attributable to the missing data (<code>lambda</code>). The pooled fit object is of class <code>mipo</code>, which stands for <em>multiply imputed pooled object</em>.</p>
<p>Alternatively, we could use a functional programming pipe to achieve the same</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> imp <span class="sc">|&gt;</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>(<span class="st">"all"</span>) <span class="sc">|&gt;</span> <span class="co"># list where each listed element is a completed set</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(lm, <span class="at">formula =</span> bmi <span class="sc">~</span> chl) <span class="sc">|&gt;</span> </span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pool</span>() <span class="sc">|&gt;</span> </span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Have a look at the different workflows that can be adopted with mice in <a href="https://stefvanbuuren.name/fimd/workflow.html">this chapter in Van Buuren’s book</a>.</p>
<p><code>mice</code> can to pool many analyses from a variety of packages for you (it uses <code>broom</code> to gather all parameters). For flexibility and in order to run custom pooling functions, mice also incorporates a function <code>pool.scalar()</code> which pools univariate estimates of <span class="math inline">\(m\)</span> repeated complete data analysis conform Rubin’s pooling rules (Rubin, 1987, paragraph 3.1)</p>
<hr>
</section>
<section id="the-boys-data-set" class="level1">
<h1>The <code>boys</code> data set</h1>
<hr>
<p><strong>9. The <code>boys</code> dataset is part of <code>mice</code>. It is a subset of a large Dutch dataset containing growth measures from the Fourth Dutch Growth Study. Inspect the help for <code>boys</code> dataset and make yourself familiar with its contents.</strong></p>
<p>To learn more about the contents of the data, use one of the two following help commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>starting httpd help server ... done</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>?boys</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>10. Get an overview of the data. Find information about the size of the data, the variables measured and the amount of missingness.</strong></p>
<p>The first 10 cases are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(boys, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age  hgt   wgt   bmi   hc  gen  phb tv   reg
3  0.035 50.1 3.650 14.54 33.7 &lt;NA&gt; &lt;NA&gt; NA south
4  0.038 53.5 3.370 11.77 35.0 &lt;NA&gt; &lt;NA&gt; NA south
18 0.057 50.0 3.140 12.56 35.2 &lt;NA&gt; &lt;NA&gt; NA south
23 0.060 54.5 4.270 14.37 36.7 &lt;NA&gt; &lt;NA&gt; NA south
28 0.062 57.5 5.030 15.21 37.3 &lt;NA&gt; &lt;NA&gt; NA south
36 0.068 55.5 4.655 15.11 37.0 &lt;NA&gt; &lt;NA&gt; NA south
37 0.068 52.5 3.810 13.82 34.9 &lt;NA&gt; &lt;NA&gt; NA south
38 0.071 53.0 3.890 13.84 35.8 &lt;NA&gt; &lt;NA&gt; NA  west
39 0.071 55.1 3.880 12.77 36.8 &lt;NA&gt; &lt;NA&gt; NA  west
43 0.073 54.5 4.200 14.14 38.0 &lt;NA&gt; &lt;NA&gt; NA  east</code></pre>
</div>
</div>
<p>The last 10 cases are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(boys, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        age   hgt  wgt   bmi   hc  gen  phb tv   reg
7329 20.032 184.0 73.0 21.56 56.0 &lt;NA&gt; &lt;NA&gt; NA north
7362 20.117 188.7 89.4 25.10 58.1   G5   P6 25  east
7396 20.281 185.1 81.1 23.67 58.8   G5   P6 20 south
7405 20.323 182.5 69.0 20.71 59.0 &lt;NA&gt; &lt;NA&gt; NA north
7410 20.372 188.7 59.8 16.79 55.2 &lt;NA&gt; &lt;NA&gt; NA  west
7418 20.429 181.1 67.2 20.48 56.6 &lt;NA&gt; &lt;NA&gt; NA north
7444 20.761 189.1 88.0 24.60   NA &lt;NA&gt; &lt;NA&gt; NA  west
7447 20.780 193.5 75.4 20.13   NA &lt;NA&gt; &lt;NA&gt; NA  west
7451 20.813 189.0 78.0 21.83 59.9 &lt;NA&gt; &lt;NA&gt; NA north
7475 21.177 181.8 76.5 23.14   NA &lt;NA&gt; &lt;NA&gt; NA  east</code></pre>
</div>
</div>
<p>We now have a clear indication that the data are sorted. A simple evaluation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span><span class="fu">is.unsorted</span>(boys<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>confirms this - <code>!is.unsorted()</code> evaluates the complement of <code>is.unsorted()</code>, so it tests whether the data are sorted. There is no <code>is.sorted</code> function in <code>R</code>.</p>
<p>The dimensions of the <code>boys</code> data set are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 748   9</code></pre>
</div>
</div>
<p>We see that the <code>boys</code> data set has 748 cases over 9 variables. From those 9 variables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age              hgt              wgt              bmi       
 Min.   : 0.035   Min.   : 50.00   Min.   :  3.14   Min.   :11.77  
 1st Qu.: 1.581   1st Qu.: 84.88   1st Qu.: 11.70   1st Qu.:15.90  
 Median :10.505   Median :147.30   Median : 34.65   Median :17.45  
 Mean   : 9.159   Mean   :132.15   Mean   : 37.15   Mean   :18.07  
 3rd Qu.:15.267   3rd Qu.:175.22   3rd Qu.: 59.58   3rd Qu.:19.53  
 Max.   :21.177   Max.   :198.00   Max.   :117.40   Max.   :31.74  
                  NA's   :20       NA's   :4        NA's   :21     
       hc          gen        phb            tv           reg     
 Min.   :33.70   G1  : 56   P1  : 63   Min.   : 1.00   north: 81  
 1st Qu.:48.12   G2  : 50   P2  : 40   1st Qu.: 4.00   east :161  
 Median :53.00   G3  : 22   P3  : 19   Median :12.00   west :239  
 Mean   :51.51   G4  : 42   P4  : 32   Mean   :11.89   south:191  
 3rd Qu.:56.00   G5  : 75   P5  : 50   3rd Qu.:20.00   city : 73  
 Max.   :65.00   NA's:503   P6  : 41   Max.   :25.00   NA's :  3  
 NA's   :46                 NA's:503   NA's   :522                </code></pre>
</div>
</div>
<p>function <code>summary()</code> informs us that testicular volume <code>tv</code> has the most missings, followed by the genital and pubic hair stages <code>gen</code> and <code>phb</code>, each with 503 missing cells.</p>
<hr>
<p><strong>11. As we have seen before, the function <code>plot_pattern()</code> can be used to display all different missing data patterns. How many different missing data patterns are present in the boys dataframe and which pattern occurs most frequently in the data?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_pattern</span>(boys)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are 13 patterns in total, with the pattern where <code>gen</code>, <code>phb</code> and <code>tv</code> are missing occuring the most.</p>
<hr>
<p><strong>12. How many patterns occur for which the variable <code>gen</code> (genital Tannerstage) is missing?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>mpat <span class="ot">&lt;-</span> <span class="fu">md.pattern</span>(boys, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(mpat[, <span class="st">"gen"</span>] <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>Answer: 8 patterns (503 cases)</p>
<hr>
<p><strong>13. Let us focus more precisely on the missing data patterns. Does the missing data of <code>gen</code> depend on <code>age</code>? One could for example check this by making a histogram of <code>age</code> separately for the cases with known genital stages and for cases with missing genital stages.</strong></p>
<p>To create said histogram in <code>R</code>, a missingness indicator for <code>gen</code> has to be created. A missingness indicator is a dummy variable with value <code>1</code> for observed values (in this case genital status) and <code>0</code> for missing values. Create a missingness indicator for <code>gen</code> by typing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">is.na</span>(boys<span class="sc">$</span>gen) </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(R, <span class="at">n =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(R, <span class="at">n =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE
 [13]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE
 [25] FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE
 [37]  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE
 [49]  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE
 [61] FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE
 [73] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE
 [85] FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE
 [97]  TRUE  TRUE  TRUE  TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(R)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 748</code></pre>
</div>
</div>
<p>As we can see, the missingness indicator tells us for each of the 748 values in <code>gen</code> whether it is missing (<code>TRUE</code>) or observed (<code>FALSE</code>).</p>
<p>A histogram can be made with</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggmice</span>(boys, <span class="fu">aes</span>(gen)) <span class="sc">+</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The code for a conditional histogram of <code>age</code> given <code>R</code> is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggmice</span>(<span class="fu">cbind</span>(boys, R), <span class="fu">aes</span>(age)) <span class="sc">+</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>R)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The histogram shows that the missingness in <code>gen</code> is not equally distributed across <code>age</code>; or, equivalently, <code>age</code> seems to be differently distributed for observed and missing <code>gen</code>.</p>
<hr>
<p><strong>14. Impute the <code>boys</code> dataset with mice using all default settings and name the <code>mids</code> (multiply imputed data set) object <code>imp</code>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(boys, <span class="at">print =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>15. Compare the means of the imputed data with the means of the incomplete data.</strong> First, we calculate the observed data means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>boys <span class="sc">|&gt;</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>phb, <span class="sc">-</span>gen, <span class="sc">-</span>reg) <span class="sc">|&gt;</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colMeans</span>(<span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       age        hgt        wgt        bmi         hc         tv 
  9.158866 132.151786  37.153187  18.068556  51.505983  11.893805 </code></pre>
</div>
</div>
<p>and then the means for the <span class="math inline">\(m\)</span> imputed sets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>imp <span class="sc">|&gt;</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  mice<span class="sc">::</span><span class="fu">complete</span>(<span class="st">"all"</span>) <span class="sc">|&gt;</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(select, <span class="sc">-</span>phb, <span class="sc">-</span>gen, <span class="sc">-</span>reg) <span class="sc">|&gt;</span>  </span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(colMeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`1`
       age        hgt        wgt        bmi         hc         tv 
  9.158866 131.056684  37.121071  18.048890  51.641310   8.307487 

$`2`
       age        hgt        wgt        bmi         hc         tv 
  9.158866 131.109759  37.126967  18.031885  51.624733   8.344920 

$`3`
       age        hgt        wgt        bmi         hc         tv 
  9.158866 131.025000  37.134386  18.052019  51.625802   8.423797 

$`4`
       age        hgt        wgt        bmi         hc         tv 
  9.158866 131.076738  37.175897  18.054626  51.656952   8.220588 

$`5`
       age        hgt        wgt        bmi         hc         tv 
  9.158866 131.132487  37.132354  18.036604  51.644118   9.108289 </code></pre>
</div>
</div>
<p>Most means are roughly equal, except the mean of <code>tv</code>, which is much lower in the imputed data sets, when compared to the incomplete data. This makes sense because most genital measures are unobserved for the lower ages. When imputing these values, the means should decrease.</p>
<p>Investigating univariate properties by using functions such as <code>summary()</code>, may not be ideal in the case of hundreds of variables. To extract just the information you need, for all imputed datasets, we can make use of the <code>with()</code> function. To obtain summaries for each imputed <code>tv</code> only, type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>imp <span class="sc">|&gt;</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">summary</span>(tv)) <span class="sc">|&gt;</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 6
  minimum    q1 median  mean    q3 maximum
    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1       1     2      3  8.31    15      25
2       1     2      3  8.34    15      25
3       1     2      3  8.42    15      25
4       1     2      3  8.22    15      25
5       1     3      5  9.11    15      25</code></pre>
</div>
</div>
<p>And to obtain e.g.&nbsp;the means alone, run</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>imp <span class="sc">|&gt;</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">mean</span>(tv)) <span class="sc">|&gt;</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 1
      x
  &lt;dbl&gt;
1  8.31
2  8.34
3  8.42
4  8.22
5  9.11</code></pre>
</div>
</div>
<hr>
</section>
<section id="repeated-analysis-in-mice-2" class="level1">
<h1>Repeated analysis in <code>mice</code> #2</h1>
<p><strong>16. Calculate a correlation between all continuous variables for the imputed <code>boys</code> data</strong></p>
<p>There are two ways in which we can calculate the correlation on the imputed data:</p>
<ul>
<li><strong>The wrong way: calculate an estimate over the <em>average imputed dataset</em> </strong>.</li>
</ul>
<p>Quite often people are suggesting that using the average imputed dataset - so taking the average over the imputed data set such that any realized cell depicts the average over the corresponding data in the imputed data - would be efficient and conform Rubin’s rules. This is not true. Doing this will yield false inference.</p>
<p>To demonstrate this, let’s create the averaged data set and exclude the non-numerical columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>ave <span class="ot">&lt;-</span> imp <span class="sc">|&gt;</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  mice<span class="sc">::</span><span class="fu">complete</span>(<span class="st">"long"</span>) <span class="sc">|&gt;</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(.id) <span class="sc">|&gt;</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(<span class="at">.funs =</span> mean) <span class="sc">|&gt;</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>.id, <span class="sc">-</span>.imp, <span class="sc">-</span>phb, <span class="sc">-</span>gen, <span class="sc">-</span>reg)</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ave)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
    age   hgt   wgt   bmi    hc    tv
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.035  50.1  3.65  14.5  33.7   5.6
2 0.038  53.5  3.37  11.8  35     4.8
3 0.057  50    3.14  12.6  35.2   3.6
4 0.06   54.5  4.27  14.4  36.7   4.6
5 0.062  57.5  5.03  15.2  37.3   1.6
6 0.068  55.5  4.66  15.1  37     2.2</code></pre>
</div>
</div>
<p>If we now calculate Pearson’s correlation, rounded to two digits:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>cor.wrong <span class="ot">&lt;-</span> ave <span class="sc">|&gt;</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>() <span class="sc">|&gt;</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we obtain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>cor.wrong</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age  hgt  wgt  bmi   hc   tv
age 1.00 0.98 0.95 0.63 0.86 0.85
hgt 0.98 1.00 0.94 0.60 0.91 0.79
wgt 0.95 0.94 1.00 0.79 0.84 0.86
bmi 0.63 0.60 0.79 1.00 0.59 0.65
hc  0.86 0.91 0.84 0.59 1.00 0.66
tv  0.85 0.79 0.86 0.65 0.66 1.00</code></pre>
</div>
</div>
<ul>
<li><strong>The correct way: calculate an estimate for each imputed dataset and average over the estimates</strong></li>
</ul>
<p>It is best to do a <a href="https://en.wikipedia.org/wiki/Fisher_transformation">Fisher transformation</a> before pooling the correlation estimates - and a backtransformation afterwards. Therefore we define the following two functions that allow us to transform and backtransform any value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>fisher.trans <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span><span class="dv">2</span> <span class="sc">*</span> <span class="fu">log</span>((<span class="dv">1</span> <span class="sc">+</span> x) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> x))</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>fisher.backtrans <span class="ot">&lt;-</span> <span class="cf">function</span>(x) (<span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">*</span> x) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (<span class="fu">exp</span>(<span class="dv">2</span> <span class="sc">*</span> x) <span class="sc">+</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, to calculate the correlation on the imputed data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>cor <span class="ot">&lt;-</span> imp <span class="sc">|&gt;</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  mice<span class="sc">::</span><span class="fu">complete</span>(<span class="st">"all"</span>) <span class="sc">|&gt;</span></span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(select, <span class="sc">-</span>phb, <span class="sc">-</span>gen, <span class="sc">-</span>reg) <span class="sc">|&gt;</span>  </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(stats<span class="sc">::</span>cor) <span class="sc">|&gt;</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(fisher.trans)</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>cor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`1`
          age       hgt      wgt       bmi        hc        tv
age       Inf 2.1949403 1.837254 0.7356147 1.2732322 1.1859803
hgt 2.1949403       Inf 1.771585 0.6838332 1.5095503 1.0238142
wgt 1.8372538 1.7715847      Inf 1.0738878 1.2025601 1.1933320
bmi 0.7356147 0.6838332 1.073888       Inf 0.6782413 0.7312594
hc  1.2732322 1.5095503 1.202560 0.6782413       Inf 0.7778726
tv  1.1859803 1.0238142 1.193332 0.7312594 0.7778726       Inf

$`2`
          age       hgt      wgt       bmi        hc        tv
age       Inf 2.1933098 1.834600 0.7381291 1.2791287 1.1800455
hgt 2.1933098       Inf 1.767965 0.6857472 1.5277852 1.0355560
wgt 1.8346001 1.7679653      Inf 1.0805352 1.2155399 1.2034901
bmi 0.7381291 0.6857472 1.080535       Inf 0.6812049 0.7158094
hc  1.2791287 1.5277852 1.215540 0.6812049       Inf 0.7697027
tv  1.1800455 1.0355560 1.203490 0.7158094 0.7697027       Inf

$`3`
          age      hgt      wgt       bmi        hc        tv
age       Inf 2.195440 1.839151 0.7384724 1.2829259 1.2040750
hgt 2.1954397      Inf 1.772119 0.6854250 1.5267638 1.0527171
wgt 1.8391513 1.772119      Inf 1.0765435 1.2171594 1.2395049
bmi 0.7384724 0.685425 1.076543       Inf 0.6823121 0.7446494
hc  1.2829259 1.526764 1.217159 0.6823121       Inf 0.7758109
tv  1.2040750 1.052717 1.239505 0.7446494 0.7758109       Inf

$`4`
          age       hgt      wgt       bmi        hc        tv
age       Inf 2.1824689 1.834547 0.7407958 1.2714558 1.1754389
hgt 2.1824689       Inf 1.765802 0.6854511 1.5165493 1.0165363
wgt 1.8345468 1.7658025      Inf 1.0816329 1.2026905 1.2055730
bmi 0.7407958 0.6854511 1.081633       Inf 0.6720943 0.7510037
hc  1.2714558 1.5165493 1.202691 0.6720943       Inf 0.7804759
tv  1.1754389 1.0165363 1.205573 0.7510037 0.7804759       Inf

$`5`
          age       hgt       wgt       bmi        hc        tv
age       Inf 2.1900726 1.8357711 0.7315571 1.2689425 0.9237541
hgt 2.1900726       Inf 1.7680711 0.6786840 1.5198465 0.8088187
wgt 1.8357711 1.7680711       Inf 1.0704767 1.2074678 0.9768873
bmi 0.7315571 0.6786840 1.0704767       Inf 0.6717104 0.6434384
hc  1.2689425 1.5198465 1.2074678 0.6717104       Inf 0.5976136
tv  0.9237541 0.8088187 0.9768873 0.6434384 0.5976136       Inf</code></pre>
</div>
</div>
<p>The object <code>cor</code> is a list over the <span class="math inline">\(m\)</span> imputations where each listed index is a correlation <code>matrix</code>. To calculate the average over the correlation matrices, we can add the <span class="math inline">\(m\)</span> listed indices and divide them by <span class="math inline">\(m\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>cor.rect <span class="ot">&lt;-</span> <span class="fu">Reduce</span>(<span class="st">"+"</span>, cor) <span class="sc">/</span> <span class="fu">length</span>(cor) <span class="co"># m is equal to the length of the list</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>cor.rect <span class="ot">&lt;-</span> <span class="fu">fisher.backtrans</span>(cor.rect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we compare the wrong estimates in <code>cor.wrong</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>cor.wrong</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age  hgt  wgt  bmi   hc   tv
age 1.00 0.98 0.95 0.63 0.86 0.85
hgt 0.98 1.00 0.94 0.60 0.91 0.79
wgt 0.95 0.94 1.00 0.79 0.84 0.86
bmi 0.63 0.60 0.79 1.00 0.59 0.65
hc  0.86 0.91 0.84 0.59 1.00 0.66
tv  0.85 0.79 0.86 0.65 0.66 1.00</code></pre>
</div>
</div>
<p>with the correct estimates in <code>cor.rect</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor.rect, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age  hgt  wgt  bmi   hc   tv
age  NaN 0.98 0.95 0.63 0.86 0.81
hgt 0.98  NaN 0.94 0.59 0.91 0.76
wgt 0.95 0.94  NaN 0.79 0.84 0.82
bmi 0.63 0.59 0.79  NaN 0.59 0.62
hc  0.86 0.91 0.84 0.59  NaN 0.63
tv  0.81 0.76 0.82 0.62 0.63  NaN</code></pre>
</div>
</div>
<p>We see that the wrong estimates in <code>cor.wrong</code> have the tendency to overestimate the correlation coefficient that is correctly combined following Rubin’s rules.</p>
<p>The correct estimates have a diagonal of <code>NaN</code>’s, because the tranformation of a correlation of <code>1</code> yields <code>Inf</code> and the backtransformation of <code>Inf</code> has no representation in real number space. We know the diagonal is supposed to be 1, so we can simply correct this</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(cor.rect) <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>cor.rect</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          age       hgt       wgt       bmi        hc        tv
age 1.0000000 0.9753200 0.9504353 0.6272769 0.8551838 0.8123358
hgt 0.9753200 1.0000000 0.9435116 0.5940024 0.9087149 0.7562894
wgt 0.9504353 0.9435116 1.0000000 0.7919405 0.8364044 0.8222606
bmi 0.6272769 0.5940024 0.7919405 1.0000000 0.5896391 0.6151918
hc  0.8551838 0.9087149 0.8364044 0.5896391 1.0000000 0.6293234
tv  0.8123358 0.7562894 0.8222606 0.6151918 0.6293234 1.0000000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why does the average data set not serve as a good basis for analysis?
</div>
</div>
<div class="callout-body-container callout-body">
<p>In <a href="https://stefvanbuuren.name/fimd/workflow.html"><code>FIMD v2</code>, paragraph 5.1.2</a> Stef mentions the following:</p>
<p><em>The average workflow is faster and easier than the correct methods, since there is no need to replicate the analyses <span class="math inline">\(m\)</span> times. In the words of Dempster and Rubin (1983), this workflow is</em></p>
<p><strong><em>seductive because it can lull the user into the pleasurable state of believing that the data are complete after all.</em></strong></p>
<p><em>The ensuing statistical analysis does not know which data are observed and which are missing, and treats all data values as real, which will underestimate the uncertainty of the parameters. The reported standard errors and p-values after data-averaging are generally too low. The correlations between the variables of the averaged data will be too high. For example, the correlation matrix in the average data are more extreme than the average of the <span class="math inline">\(m\)</span> correlation matrices, which is an example of ecological fallacy. As researchers tend to like low p-values and high correlations, there is a cynical reward for the analysis of the average data. However, analysis of the average data cannot give a fair representation of the uncertainties associated with the underlying data, and hence is not recommended.</em></p>
<p>So, please stay away from averaging the imputed data sets. Instead, use the correct workflow of analyzing the imputed sets seperately and combining the inference afterwards.</p>
</div>
</div>
</section>
<section id="the-importance-of-the-imputation-model" class="level1">
<h1>The importance of the imputation model</h1>
<p>The <code>mammalsleep</code> dataset is part of <code>mice</code>. It contains the Allison and Cicchetti (1976) data for mammalian species. To learn more about this data, type</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>17. Get an overview of the data.</strong></p>
<p>Find information about the size of the data, the variables measured and the amount of missingness.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    species       bw    brw sws  ps   ts  mls  gt pi sei odi
1          African elephant 6654.000 5712.0  NA  NA  3.3 38.6 645  3   5   3
2 African giant pouched rat    1.000    6.6 6.3 2.0  8.3  4.5  42  3   1   3
3                Arctic Fox    3.385   44.5  NA  NA 12.5 14.0  60  1   1   1
4    Arctic ground squirrel    0.920    5.7  NA  NA 16.5   NA  25  5   2   3
5            Asian elephant 2547.000 4603.0 2.1 1.8  3.9 69.0 624  3   5   4
6                    Baboon   10.550  179.5 9.1 0.7  9.8 27.0 180  4   4   4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      species         bw                brw         
 African elephant         : 1   Min.   :   0.005   Min.   :   0.14  
 African giant pouched rat: 1   1st Qu.:   0.600   1st Qu.:   4.25  
 Arctic Fox               : 1   Median :   3.342   Median :  17.25  
 Arctic ground squirrel   : 1   Mean   : 198.790   Mean   : 283.13  
 Asian elephant           : 1   3rd Qu.:  48.202   3rd Qu.: 166.00  
 Baboon                   : 1   Max.   :6654.000   Max.   :5712.00  
 (Other)                  :56                                       
      sws               ps              ts             mls         
 Min.   : 2.100   Min.   :0.000   Min.   : 2.60   Min.   :  2.000  
 1st Qu.: 6.250   1st Qu.:0.900   1st Qu.: 8.05   1st Qu.:  6.625  
 Median : 8.350   Median :1.800   Median :10.45   Median : 15.100  
 Mean   : 8.673   Mean   :1.972   Mean   :10.53   Mean   : 19.878  
 3rd Qu.:11.000   3rd Qu.:2.550   3rd Qu.:13.20   3rd Qu.: 27.750  
 Max.   :17.900   Max.   :6.600   Max.   :19.90   Max.   :100.000  
 NA's   :14       NA's   :12      NA's   :4       NA's   :4        
       gt               pi             sei             odi       
 Min.   : 12.00   Min.   :1.000   Min.   :1.000   Min.   :1.000  
 1st Qu.: 35.75   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.000  
 Median : 79.00   Median :3.000   Median :2.000   Median :2.000  
 Mean   :142.35   Mean   :2.871   Mean   :2.419   Mean   :2.613  
 3rd Qu.:207.50   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :645.00   Max.   :5.000   Max.   :5.000   Max.   :5.000  
 NA's   :4                                                       </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   62 obs. of  11 variables:
 $ species: Factor w/ 62 levels "African elephant",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ bw     : num  6654 1 3.38 0.92 2547 ...
 $ brw    : num  5712 6.6 44.5 5.7 4603 ...
 $ sws    : num  NA 6.3 NA NA 2.1 9.1 15.8 5.2 10.9 8.3 ...
 $ ps     : num  NA 2 NA NA 1.8 0.7 3.9 1 3.6 1.4 ...
 $ ts     : num  3.3 8.3 12.5 16.5 3.9 9.8 19.7 6.2 14.5 9.7 ...
 $ mls    : num  38.6 4.5 14 NA 69 27 19 30.4 28 50 ...
 $ gt     : num  645 42 60 25 624 180 35 392 63 230 ...
 $ pi     : int  3 3 1 5 3 4 1 4 1 1 ...
 $ sei    : int  5 1 1 2 5 4 1 5 2 1 ...
 $ odi    : int  3 3 1 3 4 4 1 4 1 1 ...</code></pre>
</div>
</div>
<p>As we have seen before, the function <code>plot_pattern()</code> can be used to display all different missing data patterns. How many different missing data patterns are present in the <code>mammalsleep</code> dataframe and which pattern occurs most frequently in the data?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_pattern</span>(mammalsleep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Answer: 8 patterns in total, with the pattern where everything is observed occuring the most (42 times).</p>
<hr>
<p><strong>18. Generate five imputed datasets with the default method <code>pmm</code>. Give the algorithm 10 iterations. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>imp1 <span class="ot">&lt;-</span> <span class="fu">mice</span>(mammalsleep, <span class="at">maxit =</span> <span class="dv">10</span>, <span class="at">print =</span> <span class="cn">FALSE</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Number of logged events: 525</code></pre>
</div>
</div>
<p>We ignore the <code>loggedEvents</code> for now: it contains a list of all decisions and exclusions that are performed by the <code>mice</code> algorithm. To inspect the trace lines for assessing algorithmic convergence:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<p><strong>19. Perform a regression analysis on the imputed dataset with <code>sws</code> as dependent variable and <code>log10(bw)</code> and <code>odi</code> as independent variables.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp1, <span class="fu">lm</span>(sws <span class="sc">~</span> <span class="fu">log10</span>(bw) <span class="sc">+</span> odi))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<p><strong>20. Pool the regression analysis and inspect the pooled analysis.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>est1 <span class="ot">&lt;-</span> <span class="fu">pool</span>(fit1)</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>est1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mipo    m = 5 
         term m   estimate       ubar          b         t dfcom        df
1 (Intercept) 5 10.4531011 0.74118963 1.14943174 2.1205077    59  6.415045
2   log10(bw) 5 -1.2208246 0.10463333 0.43904955 0.6314928    59  3.575000
3         odi 5 -0.5903973 0.09266979 0.01099559 0.1058645    59 41.855897
        riv    lambda       fmi
1 1.8609517 0.6504660 0.7247161
2 5.0352929 0.8343080 0.8847086
3 0.1423841 0.1246377 0.1636677</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         term   estimate std.error statistic        df      p.value
1 (Intercept) 10.4531011 1.4561963  7.178360  6.415045 0.0002722293
2   log10(bw) -1.2208246 0.7946652 -1.536275  3.575000 0.2075295973
3         odi -0.5903973 0.3253683 -1.814551 41.855897 0.0767643303</code></pre>
</div>
</div>
<p>The <code>fmi</code> and <code>lambda</code> are much too high. This is due to <code>species</code> being included in the imputation model. Because there are 62 species and mice automatically converts factors (categorical variables) to dummy variables, each species is modeled by its own imputation model.</p>
<hr>
<p><strong>21. Impute <code>mammalsleep</code> again, but now exclude <code>species</code> from the data.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>imp2 <span class="ot">&lt;-</span> <span class="fu">mice</span>(mammalsleep[ , <span class="sc">-</span><span class="dv">1</span>], <span class="at">maxit =</span> <span class="dv">10</span>, <span class="at">print =</span> <span class="cn">FALSE</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Number of logged events: 16</code></pre>
</div>
</div>
<hr>
<p><strong>22. Compute and pool the regression analysis again. </strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">with</span>(imp2, <span class="fu">lm</span>(sws <span class="sc">~</span> <span class="fu">log10</span>(bw) <span class="sc">+</span> odi))</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>est2 <span class="ot">&lt;-</span> <span class="fu">pool</span>(fit2)</span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>est2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Class: mipo    m = 5 
         term m   estimate       ubar           b          t dfcom       df
1 (Intercept) 5 11.5743466 0.58482690 0.028813743 0.61940339    59 51.73671
2   log10(bw) 5 -1.1673462 0.08255969 0.003652185 0.08694231    59 52.41337
3         odi 5 -0.8938741 0.07312000 0.001569891 0.07500387    59 55.17827
         riv     lambda        fmi
1 0.05912261 0.05582225 0.09032114
2 0.05308428 0.05040839 0.08468140
3 0.02576407 0.02511696 0.05863060</code></pre>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         term   estimate std.error statistic       df      p.value
1 (Intercept) 11.5743466 0.7870218 14.706512 51.73671 4.056406e-20
2   log10(bw) -1.1673462 0.2948598 -3.958987 52.41337 2.279692e-04
3         odi -0.8938741 0.2738683 -3.263883 55.17827 1.889640e-03</code></pre>
</div>
</div>
<p>Note that the <code>fmi</code> and <code>lambda</code> have dramatically decreased. The imputation model has been greatly improved.</p>
<hr>
<p><strong>23. Plot the trace lines for the new imputations</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Even though the fraction of information missing due to nonresponse (fmi) and the relative increase in variance due to nonresponse (lambda) are nice and low, the convergence turns out to be a real problem. The reason is the structure in the data. Total sleep (<code>ts</code>) is the sum of paradoxical sleep (<code>ps</code>) and short wave sleep (<code>sws</code>). This relation is ignored in the imputations, but it is necessary to take this relation into account. <code>mice</code> offers a routine called <em>passive imputation</em>, which allows users to take transformations, combinations and recoded variables into account when imputing their data.</p>
<hr>
</section>
<section id="passive-imputation" class="level1">
<h1>Passive Imputation</h1>
<p>There is often a need for transformed, combined or recoded versions of the data. In the case of incomplete data, one could impute the original, and transform the completed original afterwards, or transform the incomplete original and impute the transformed version. IFALSE, however, both the original and the transformed version are needed within the imputation algorithm, neither of these approaches work: One cannot be sure that the transformation holds between the imputed values of the original and transformed versions. <code>mice</code> has a built-in approach, called <em>passive imputation</em>, to deal with situations as described above. The goal of passive imputation is to maintain the consistency among different transformations of the same data. As an example, consider the following deterministic function in the <code>boys</code> data [ = ] or the compositional relation in the mammalsleep data: [ = +]</p>
<hr>
<p><strong>24. Use passive imputation to impute the deterministic sleep relation in the <code>mammalsleep</code> data. Name the new multiply imputed dataset <code>pas.imp</code>.</strong></p>
<p>First, we create a <code>method</code> vector:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>meth <span class="ot">&lt;-</span> <span class="fu">make.method</span>(mammalsleep)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>species      bw     brw     sws      ps      ts     mls      gt      pi     sei 
     ""      ""      ""   "pmm"   "pmm"   "pmm"   "pmm"   "pmm"      ""      "" 
    odi 
     "" </code></pre>
</div>
</div>
<p>and a <code>predictorMatrix</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">make.predictorMatrix</span>(mammalsleep)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species bw brw sws ps ts mls gt pi sei odi
species       0  1   1   1  1  1   1  1  1   1   1
bw            1  0   1   1  1  1   1  1  1   1   1
brw           1  1   0   1  1  1   1  1  1   1   1
sws           1  1   1   0  1  1   1  1  1   1   1
ps            1  1   1   1  0  1   1  1  1   1   1
ts            1  1   1   1  1  0   1  1  1   1   1
mls           1  1   1   1  1  1   0  1  1   1   1
gt            1  1   1   1  1  1   1  0  1   1   1
pi            1  1   1   1  1  1   1  1  0   1   1
sei           1  1   1   1  1  1   1  1  1   0   1
odi           1  1   1   1  1  1   1  1  1   1   0</code></pre>
</div>
</div>
<p>We add the call for passive imputation to the <code>ts</code> element in the <code>meth</code> object</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"ts"</span>]<span class="ot">&lt;-</span> <span class="st">"~ I(sws + ps)"</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>meth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species              bw             brw             sws              ps 
             ""              ""              ""           "pmm"           "pmm" 
             ts             mls              gt              pi             sei 
"~ I(sws + ps)"           "pmm"           "pmm"              ""              "" 
            odi 
             "" </code></pre>
</div>
</div>
<p>and set the predictor relations for <code>ts</code> with <code>sws</code> and <code>ps</code> to <code>0</code>. Also, we have to exclude <code>Species</code> as a predictor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>pred[<span class="fu">c</span>(<span class="st">"sws"</span>, <span class="st">"ps"</span>), <span class="st">"ts"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>pred[, <span class="st">"species"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species bw brw sws ps ts mls gt pi sei odi
species       0  1   1   1  1  1   1  1  1   1   1
bw            0  0   1   1  1  1   1  1  1   1   1
brw           0  1   0   1  1  1   1  1  1   1   1
sws           0  1   1   0  1  0   1  1  1   1   1
ps            0  1   1   1  0  0   1  1  1   1   1
ts            0  1   1   1  1  0   1  1  1   1   1
mls           0  1   1   1  1  1   0  1  1   1   1
gt            0  1   1   1  1  1   1  0  1   1   1
pi            0  1   1   1  1  1   1  1  0   1   1
sei           0  1   1   1  1  1   1  1  1   0   1
odi           0  1   1   1  1  1   1  1  1   1   0</code></pre>
</div>
</div>
<p>This avoids circularity problems where <code>ts</code> would <em>feed back into</em> <code>sws</code> and <code>ps</code>, from which it is calculated:</p>
<p>We can then run the imputations as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>pas.imp <span class="ot">&lt;-</span> <span class="fu">mice</span>(mammalsleep, </span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">meth =</span> meth, </span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">pred =</span> pred, </span>
<span id="cb141-4"><a href="#cb141-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">maxit =</span> <span class="dv">50</span>, </span>
<span id="cb141-5"><a href="#cb141-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">seed =</span> <span class="dv">123</span>, </span>
<span id="cb141-6"><a href="#cb141-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">print =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We used a custom predictor matrix and method vector to tailor our imputation approach to the passive imputation problem. We made sure to exclude <code>ts</code> as a predictor for the imputation of <code>sws</code> and <code>ps</code> to avoid circularity.</p>
<p>We also gave the imputation algorithm 10 iterations to converge and fixed the seed to <code>123</code> for this <code>mice</code> instance. This means that even when people do not fix the overall <code>R</code> seed for a session, exact replication of results can be obtained by simply fixing the <code>seed</code> for the random number generator within <code>mice</code>. Naturally, the same input (data) is each time required to yield the same output (<code>mids</code>-object).</p>
<p>When we study convergence, we see that the apparent non-convergence that we saw before has now disappeared with the use of passive imputation for the deterministic system <code>(ts, ps, sws)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(pas.imp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-75-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
<section id="for-fun" class="level2">
<h2 class="anchored" data-anchor-id="for-fun">For fun</h2>
<p><strong>What you shouldn’t do with passive imputation!</strong></p>
<p>Never set all relations fixed. You will remain with the starting values and waste your computer’s energy (and your own).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>meth <span class="ot">&lt;-</span> <span class="fu">make.method</span>(boys)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">make.predictorMatrix</span>(boys)</span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"bmi"</span>] <span class="ot">&lt;-</span> <span class="st">"~ I(wgt / (hgt / 100)^2)"</span></span>
<span id="cb143-4"><a href="#cb143-4" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"wgt"</span>] <span class="ot">&lt;-</span> <span class="st">"~ I(bmi * (hgt / 100)^2)"</span></span>
<span id="cb143-5"><a href="#cb143-5" aria-hidden="true" tabindex="-1"></a>meth[<span class="st">"hgt"</span>] <span class="ot">&lt;-</span> <span class="st">"~ I(sqrt(wgt / bmi) * 100)"</span></span>
<span id="cb143-6"><a href="#cb143-6" aria-hidden="true" tabindex="-1"></a>pred[<span class="fu">c</span>(<span class="st">"bmi"</span>, <span class="st">"wgt"</span>, <span class="st">"hgt"</span>), ] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb143-7"><a href="#cb143-7" aria-hidden="true" tabindex="-1"></a>imp.path <span class="ot">&lt;-</span> <span class="fu">mice</span>(boys, </span>
<span id="cb143-8"><a href="#cb143-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">meth=</span>meth, </span>
<span id="cb143-9"><a href="#cb143-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">pred=</span>pred, </span>
<span id="cb143-10"><a href="#cb143-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">seed=</span><span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  hgt  wgt  bmi  hc  gen  phb  tv  reg
  1   2  hgt  wgt  bmi  hc  gen  phb  tv  reg
  1   3  hgt  wgt  bmi  hc  gen  phb  tv  reg
  1   4  hgt  wgt  bmi  hc  gen  phb  tv  reg
  1   5  hgt  wgt  bmi  hc  gen  phb  tv  reg
  2   1  hgt  wgt  bmi  hc  gen  phb  tv  reg
  2   2  hgt  wgt  bmi  hc  gen  phb  tv  reg
  2   3  hgt  wgt  bmi  hc  gen  phb  tv  reg
  2   4  hgt  wgt  bmi  hc  gen  phb  tv  reg
  2   5  hgt  wgt  bmi  hc  gen  phb  tv  reg
  3   1  hgt  wgt  bmi  hc  gen  phb  tv  reg
  3   2  hgt  wgt  bmi  hc  gen  phb  tv  reg
  3   3  hgt  wgt  bmi  hc  gen  phb  tv  reg
  3   4  hgt  wgt  bmi  hc  gen  phb  tv  reg
  3   5  hgt  wgt  bmi  hc  gen  phb  tv  reg
  4   1  hgt  wgt  bmi  hc  gen  phb  tv  reg
  4   2  hgt  wgt  bmi  hc  gen  phb  tv  reg
  4   3  hgt  wgt  bmi  hc  gen  phb  tv  reg
  4   4  hgt  wgt  bmi  hc  gen  phb  tv  reg
  4   5  hgt  wgt  bmi  hc  gen  phb  tv  reg
  5   1  hgt  wgt  bmi  hc  gen  phb  tv  reg
  5   2  hgt  wgt  bmi  hc  gen  phb  tv  reg
  5   3  hgt  wgt  bmi  hc  gen  phb  tv  reg
  5   4  hgt  wgt  bmi  hc  gen  phb  tv  reg
  5   5  hgt  wgt  bmi  hc  gen  phb  tv  reg</code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_trace</span>(imp.path, <span class="fu">c</span>(<span class="st">"hgt"</span>, <span class="st">"wgt"</span>, <span class="st">"bmi"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-76-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We named the <code>mids</code> object <code>imp.path</code>, because the nonconvergence is pathological in this example!</p>
<hr>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>We have seen that the practical execution of multiple imputation and pooling is straightforward with the <code>R</code> package <code>mice</code>. The package is designed to allow you to assess and control the imputations themselves, the convergence of the algorithm and the distributions and multivariate relations of the observed and imputed data.</p>
<p>It is important to ‘gain’ this control as a user. After all, we are imputing values and we aim to properly adress the uncertainty about the missingness problem.</p>
<hr>
</section>
<section id="additional-materials" class="level1">
<h1>Additional materials</h1>
<p>A more detailed practical guide to <code>mice</code> in <code>R</code> can be found <a href="https://www.gerkovink.com/miceVignettes/">here</a></p>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Rubin, D. B. <em>Multiple imputation for nonresponse in surveys</em>. John Wiley &amp; Sons, 1987. <a href="http://www.amazon.com/Multiple-Imputation-Nonresponse-Surveys-Donald/dp/0471655740/ref=sr_1_1?ie=UTF8&amp;qid=1434466788&amp;sr=8-1&amp;keywords=Multiple+imputation+for+nonresponse+in+surveys">Amazon</a></p>
<p>Schafer, J.L. (1997). <em>Analysis of Incomplete Multivariate Data</em>. London: Chapman &amp; Hall. Table 6.14. <a href="http://www.amazon.com/Incomplete-Multivariate-Monographs-Statistics-Probability/dp/0412040611/ref=sr_1_1?ie=UTF8&amp;qid=1434466828&amp;sr=8-1&amp;keywords=Analysis+of+Incomplete+Multivariate+Data">Amazon</a></p>
<p>Van Buuren, S. and Groothuis-Oudshoorn, K. (2011). mice: Multivariate Imputation by Chained Equations in R. <em>Journal of Statistical Software</em>, 45(3), 1-67. <a href="http://www.jstatsoft.org/v45/i03/paper">pdf</a></p>
<hr>
<p><strong>- End of practical</strong></p>
<hr>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Dutch_Netherlands.utf8  LC_CTYPE=Dutch_Netherlands.utf8   
[3] LC_MONETARY=Dutch_Netherlands.utf8 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.utf8    

time zone: Europe/Amsterdam
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] purrr_1.0.1       dplyr_1.1.4       ggplot2_3.5.0     ggmice_0.1.0.9000
[5] mice_3.16.0      

loaded via a namespace (and not attached):
 [1] utf8_1.2.4        generics_0.1.3    tidyr_1.3.1       shape_1.4.6      
 [5] stringi_1.7.12    lattice_0.21-8    lme4_1.1-35.1     digest_0.6.31    
 [9] magrittr_2.0.3    mitml_0.4-5       evaluate_0.23     grid_4.3.0       
[13] iterators_1.0.14  fastmap_1.1.1     foreach_1.5.2     jomo_2.7-6       
[17] jsonlite_1.8.8    glmnet_4.1-8      Matrix_1.6-5      nnet_7.3-18      
[21] backports_1.4.1   survival_3.5-5    fansi_1.0.5       scales_1.3.0     
[25] codetools_0.2-19  cli_3.6.1         rlang_1.1.1       munsell_0.5.0    
[29] splines_4.3.0     withr_3.0.0       yaml_2.3.8        pan_1.9          
[33] tools_4.3.0       nloptr_2.0.3      minqa_1.2.6       colorspace_2.1-0 
[37] boot_1.3-28.1     broom_1.0.5       rpart_4.1.21      vctrs_0.6.5      
[41] R6_2.5.1          lifecycle_1.0.4   stringr_1.5.1     htmlwidgets_1.6.3
[45] MASS_7.3-58.4     pkgconfig_2.0.3   gtable_0.3.4      pillar_1.9.0     
[49] glue_1.6.2        Rcpp_1.0.10       xfun_0.41         tibble_3.2.1     
[53] tidyselect_1.2.0  rstudioapi_0.15.0 knitr_1.45        farver_2.1.1     
[57] htmltools_0.5.7   nlme_3.1-162      labeling_0.4.3    rmarkdown_2.25   
[61] compiler_4.3.0   </code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>